"""推分 / 等级进度 / 分数列表行卡体系（NB core/image/score.py 的移植）。

视觉基座：PRiSM PLUS 三色渐变底 + aurora/星光/彩虹/底纹装饰层，难度行卡用
``b50_score_*.png``（成绩）与 ``rise_score_*.png``（推分）素材，坐标对齐 NB 版。
底图尺寸由调用方按数据量计算后传入（NB handler 同款约定）。
"""

from PIL import Image
from maimai_py import RateType, SongType
from maimai_py.models import SongDifficulty

from .fonts import FONT_HAN, FONT_NUM, font
from .tools import image_to_bytes, tricolor_gradient_prism_plus
from .assets import assets
from ...config import NICKNAME
from .nb_chart import truncate_by_width
from ...constants import RATE_FILE

# 难度文字色 / 谱面 id 色（NB AssetsImage 类属性同源）
_DIFF_TEXT_COLOR = [
    (255, 255, 255, 255),
    (255, 255, 255, 255),
    (255, 255, 255, 255),
    (255, 255, 255, 255),
    (138, 0, 226, 255),
]
_ID_TEXT_COLOR = [
    (129, 217, 85, 255),
    (245, 189, 21, 255),
    (255, 129, 141, 255),
    (159, 81, 220, 255),
    (138, 0, 226, 255),
]
_DEFAULT_TEXT_COLOR = (124, 129, 255, 255)

_LEVEL_INDEXES = ("basic", "advanced", "expert", "master", "remaster")
"""难度序 → 素材名后缀（rise_score_*/b50_score_*）。"""


def _rate_file_of(achievement: float) -> str:
    """达成率 → 评级徽章文件名后缀（UI_TTR_Rank_*）。"""
    rate = RateType._from_achievement(achievement)
    return RATE_FILE[rate.name]


class DrawScore:
    """行卡画布：构造时生成装饰底图，draw_* 系列输出成品 bytes。"""

    def __init__(self, height: int, *, service: str | None = None) -> None:
        base = assets.static_path() / "mai" / "pic"
        theme = "prism_plus"
        im = tricolor_gradient_prism_plus(1400, height)
        im.alpha_composite(assets.pic("aurora.png"))
        im.alpha_composite(assets.pic("bg_shines.png"), (11, 6))
        im.alpha_composite(assets.pic("rainbow.png"), (318, height - 545))
        im.alpha_composite(assets.pic("rainbow_bottom.png"), (122, height - 305))
        pattern = assets.pic("pattern.png")
        for h in range(height // 358 + 1):
            im.alpha_composite(pattern, (0, (358 + 7) * h))
        self._im = im
        self._base = base
        self._theme = theme
        self._title_bg = assets.pic("title.png", theme)
        self._title_lengthen_bg = assets.pic("title_lengthen.png", theme)
        # NB 版式：装饰层先贴，标题底图与文字随后（构造时只备料）
        self._service = service

    def _design_text(self) -> str:
        text = "Designed by Yuri-YuzuChaN & BlueDeer233."
        if self._service:
            text += f" Data from {self._service}."
        return f"{text} Generated by {NICKNAME or 'awmc-helper'} BOT"

    # -- 推分推荐卡（R3，NB draw_rise / while_rise_pic） ---------------------

    def _while_rise_pic(self, data: list[dict], base_x: int) -> None:
        """循环绘制上分推荐行卡。

        ``data`` 元素为 :func:`core.calc.rise_recommend` 的输出 dict（含 old_*）；
        ``base_x``：栏起点（SD 栏 200 / DX 栏 700，与 NB 一致）。
        """
        from PIL import ImageDraw

        dr = ImageDraw.Draw(self._im)
        start_y, step = 120, 140
        for index, row in enumerate(data):
            diff: SongDifficulty = row["diff"]
            song = row["song"]
            li = diff.level_index.value
            x = base_x
            y = start_y + index * step

            self._im.alpha_composite(
                assets.pic(f"rise_score_{_LEVEL_INDEXES[li]}.png"), (x + 30, y)
            )
            self._im.alpha_composite(
                assets.cover(song.id).resize((80, 80)), (x + 55, y + 41)
            )
            type_abbr = "DX" if diff.type == SongType.DX else "SD"
            type_path = self._base / f"{type_abbr}.png"
            if type_path.exists():
                self._im.alpha_composite(
                    Image.open(type_path).convert("RGBA").resize((60, 22)),
                    (x + 240, y + 114),
                )
            # 旧成绩评级（未游玩按 D 显示，对齐 NB 默认值）
            old_ach = row.get("old_achievements") or 0
            self._im.alpha_composite(
                assets.pic(
                    f"UI_TTR_Rank_{_rate_file_of(old_ach)}.png", self._theme
                ).resize((63, 28)),
                (x + 145, y + 82),
            )
            self._im.alpha_composite(
                assets.pic(
                    f"UI_TTR_Rank_{_rate_file_of(row['achievements'])}.png",
                    self._theme,
                ).resize((63, 28)),
                (x + 305, y + 82),
            )

            diff_color = _DIFF_TEXT_COLOR[li]
            id_color = _ID_TEXT_COLOR[li]

            title = truncate_by_width(song.title, 26)
            dr.text(
                (x + 142, y + 44),
                title,
                font=font(17, FONT_HAN),
                fill=diff_color,
                anchor="lm",
            )
            dr.text(
                (x + 145, y + 124),
                f"ID: {song.id}",
                font=font(18, FONT_NUM),
                fill=id_color,
                anchor="lm",
            )
            dr.text(
                (x + 210, y + 71),
                f"{old_ach:.4f}%",
                font=font(25, FONT_NUM),
                fill=diff_color,
                anchor="mm",
            )
            dr.text(
                (x + 245, y + 96),
                f"Ra: {int(row.get('old_ra') or 0)}",
                font=font(17, FONT_NUM),
                fill=diff_color,
                anchor="mm",
            )
            dr.text(
                (x + 370, y + 71),
                f"{row['achievements']:.4f}%",
                font=font(25, FONT_NUM),
                fill=diff_color,
                anchor="mm",
            )
            dr.text(
                (x + 415, y + 96),
                f"Ra: {int(row['new_ra'])}",
                font=font(17, FONT_NUM),
                fill=diff_color,
                anchor="mm",
            )
            dr.text(
                (x + 315, y + 124),
                f"ds:{diff.level_value}",
                font=font(17, FONT_NUM),
                fill=id_color,
                anchor="lm",
            )
            dr.text(
                (x + 390, y + 124),
                f"Ra +{int(row['gain'])}",
                font=font(18, FONT_NUM),
                fill=id_color,
                anchor="lm",
            )

    def draw_rise(
        self,
        sd: list[dict],
        dx: list[dict],
        total_height: int,
    ) -> bytes:
        """绘制上分推荐表（左栏旧版本谱面 / 右栏新版本谱面，各 5 行）。"""
        from PIL import ImageDraw

        dr = ImageDraw.Draw(self._im)
        title_bg = self._title_bg.resize((273, 80))
        self._im.alpha_composite(title_bg, (314, 30))
        dr.text(
            (450, 68),
            "旧版本谱面推荐",
            font=font(18, FONT_HAN),
            fill=_DEFAULT_TEXT_COLOR,
            anchor="mm",
        )
        self._while_rise_pic(sd, 200)
        self._im.alpha_composite(title_bg, (814, 30))
        dr.text(
            (950, 68),
            "新版本谱面推荐",
            font=font(18, FONT_HAN),
            fill=_DEFAULT_TEXT_COLOR,
            anchor="mm",
        )
        self._while_rise_pic(dx, 700)

        height = self._im.size[1]
        dr.text(
            (700, height - 84),
            "「谱面推荐不使用任何算法，仅供参考」",
            font=font(25, FONT_HAN),
            fill=_DEFAULT_TEXT_COLOR,
            anchor="mm",
        )
        dr.text(
            (700, height - 36),
            self._design_text(),
            font=font(18, FONT_HAN),
            fill=_DEFAULT_TEXT_COLOR,
            anchor="mm",
            stroke_width=2,
            stroke_fill=(255, 255, 255, 255),
        )
        return image_to_bytes(self._im.crop((200, 0, 1200, total_height)))
