"""完成表「模板预渲染 + 成绩实时叠加」（NB 方案，Q7）。

模板布局 1:1 移植 NB ``core/image/update_table.py::UpdateTable``：
- 定数表底图：PRiSM 三色渐变 + 毛玻璃卡 + ``.X`` 定数节标签 + 14 列描边封面
  网格（``border_basic..remaster`` 难度框）；lv15 为三列大图（版本横幅 +
  UNKNOWN 占位）；
- 牌子完成表底图：12 列网格（``border_table_base`` id 框），舞/霸按等级 13
  分两页且 Re:MASTER 曲用紫 id（``border_table_remaster``）。

用户查询时打开底图：定数表叠「Level.」大字（``rating_table_level_text``）、
完成表叠评级/FC/Sync 印章与统计（``rating_table`` 模块 / ``plate_table_draw``
模块），底图缺失时在内存中按同布局现算，不再落盘。
"""

import asyncio
from pathlib import Path
from collections.abc import Sequence

from PIL import Image
from nonebot import logger
from maimai_py import Song, SongType, SongDifficulty

from .fonts import font
from .tools import (
    image_to_bytes,
    generate_frosted_card,
    tricolor_gradient_prism_plus,
)
from .assets import assets
from ...constants import chart_display_id

FONT_BLUE = (114, 188, 254, 255)
_LEVEL_INDEXES = ("basic", "advanced", "expert", "master", "remaster")
_DIFF_TEXT_COLOR = [
    (255, 255, 255, 255),
    (255, 255, 255, 255),
    (255, 255, 255, 255),
    (255, 255, 255, 255),
    (138, 0, 226, 255),
]


def rating_table_dir() -> Path:
    return assets.static_path() / "mai" / "rating_table"


def plate_table_dir() -> Path:
    return assets.static_path() / "mai" / "plate_table"


def _generate_bg(height: int, separator_height: int) -> Image.Image:
    """NB UpdateTable._generate_bg：三色渐变 + 装饰层 + 分割线。"""
    im = tricolor_gradient_prism_plus(1400, height)
    im.alpha_composite(assets.pic("aurora.png"))
    im.alpha_composite(assets.pic("bg_shines.png"), (11, 6))
    im.alpha_composite(assets.pic("rainbow.png"), (318, height - 545))
    im.alpha_composite(assets.pic("rainbow_bottom.png"), (122, height - 305))
    pattern = assets.pic("pattern.png")
    for h in range(height // 358 + 1):
        im.alpha_composite(pattern, (0, (358 + 7) * h))
    im.alpha_composite(assets.pic("separator.png"), (100, separator_height))
    return im


def _credit(im: Image.Image, height: int) -> None:
    from PIL import ImageDraw

    from ...config import NICKNAME

    ImageDraw.Draw(im).text(
        (700, height - 75),
        (
            "Designed by Yuri-YuzuChaN & BlueDeer233. "
            f"Generated by {NICKNAME or 'awmc-helper'} BOT"
        ),
        font=font(30, "FOT-NewRodin Pro EB.otf"),
        fill=FONT_BLUE,
        anchor="mm",
    )


def _group_by_ds(
    entries: Sequence[tuple[Song, SongDifficulty]],
) -> dict[str, list[tuple[Song, SongDifficulty]]]:
    """按定数串分组（"13.0"/"13.6"），节序按定数降序（NB by_level_list 同序）。"""
    grouped: dict[str, list[tuple[Song, SongDifficulty]]] = {}
    for song, diff in entries:
        if diff.level_value < 7:
            continue
        grouped.setdefault(f"{diff.level_value:.1f}", []).append((song, diff))
    return {k: grouped[k] for k in sorted(grouped, key=float, reverse=True)}


def _rating_grid(
    entries: Sequence[tuple[Song, SongDifficulty]],
) -> Image.Image:
    """NB update_rating_table 布局（lv7–14）：毛玻璃卡 + 定数节封面网格。"""
    GRID_STEP, START_X, START_Y = 85, 140, 450
    groups = _group_by_ds(entries)

    current_y = START_Y
    for charts in groups.values():
        rows = (len(charts) - 1) // 14 + 1
        current_y += rows * GRID_STEP + 30
    height = current_y + 230

    im = generate_frosted_card(_generate_bg(height, 360), (50, 404, 1350, current_y))
    from PIL import ImageDraw

    dr = ImageDraw.Draw(im)

    _credit(im, height)

    start_y = START_Y
    for ds, charts in groups.items():
        # 节标签 = 定数小数部分（如 ".6"）
        dr.text(
            (70, start_y + 35),
            f".{ds.split('.')[-1]}",
            font=font(40, "FOT-NewRodin Pro EB.otf"),
            fill=FONT_BLUE,
            anchor="lm",
            stroke_width=4,
            stroke_fill=(255, 255, 255, 255),
        )
        max_row = 0
        for num, (song, diff) in enumerate(charts):
            row, col = divmod(num, 14)
            max_row = max(max_row, row)
            x = START_X + col * GRID_STEP
            y = start_y + row * GRID_STEP
            li = diff.level_index.value
            im.alpha_composite(assets.cover(song.id).resize((75, 75)), (x, y))
            im.alpha_composite(
                assets.pic(f"border_{_LEVEL_INDEXES[li]}.png"), (x - 5, y - 5)
            )
            dr.text(
                (x + 56, y + 4),
                str(song.id),
                font=font(13, "Torus SemiBold.otf"),
                fill=_DIFF_TEXT_COLOR[li],
                anchor="mm",
            )
        start_y += (max_row + 1) * GRID_STEP + 30
    return im


def _rating_grid_15(
    entries: Sequence[tuple[Song, SongDifficulty]],
) -> Image.Image:
    """NB update_level_15_rating_table：lv15 三列大图（含 UNKNOWN 占位）。"""
    count = len(entries)
    lines = count // 3 + (1 if count % 3 else 0)
    height = 650 + lines * 450

    im = _generate_bg(height, 360)
    from PIL import ImageDraw

    dr = ImageDraw.Draw(im)
    _credit(im, height)

    unknown = assets.cover(0).convert("RGBA").resize((330, 330))
    for i in range(lines * 3):
        row, col = divmod(i, 3)
        x = 100 + col * 425
        y = 500 + row * 450
        im.alpha_composite(assets.pic("chart_white.png"), (x, y))
        if i < count:
            song, diff = entries[i]
            im.alpha_composite(
                assets.cover(song.id).resize((330, 330)), (x + 10, y + 10)
            )
            im.alpha_composite(
                assets.pic("DX.png" if diff.type == SongType.DX else "SD.png"),
                (x + 200, y + 345),
            )
            from .nb_chart import _version_image

            version_img = _version_image(diff.version or song.version)
            if version_img is not None:
                banner = version_img.resize((332, 160))
                im.alpha_composite(banner, (x + 9, y - 80))
            dr.text(
                (x + 100, y + 370),
                str(song.id),
                font=font(35, "FOT-NewRodin Pro EB.otf"),
                fill=FONT_BLUE,
                anchor="mm",
            )
        else:
            im.alpha_composite(unknown, (x + 10, y + 10))
            im.alpha_composite(assets.pic("DX.png"), (x + 200, y + 345))
            dr.text(
                (x + 100, y + 370),
                "????",
                font=font(35, "FOT-NewRodin Pro EB.otf"),
                fill=FONT_BLUE,
                anchor="mm",
            )
            dr.text(
                (x + 175, y + 280),
                "UNKNOWN",
                font=font(30, "FOT-NewRodin Pro EB.otf"),
                fill=FONT_BLUE,
                anchor="mm",
                stroke_width=8,
                stroke_fill=(255, 255, 255, 255),
            )
    return im


def _plate_grid(
    entries: Sequence[tuple[Song, SongDifficulty]],
    major_type: SongType,
    *,
    remaster_entries: Sequence[tuple[Song, SongDifficulty]] | None = None,
    pages: int | None = None,
) -> Image.Image:
    """NB _draw_plate 布局：牌子完成表底图（12 列，ReM 曲紫 id）。"""
    GRID_STEP, START_X, START_Y = 96, 180, 490
    remaster_ids = {s.id for s, _d in (remaster_entries or [])}

    # 按 MASTER 槽等级分组（舞/霸的 ReM 曲用 ReM 槽等级）
    def level_of(song: Song, diff: SongDifficulty) -> str:
        if remaster_entries and song.id in remaster_ids:
            re_m = next(
                (
                    d
                    for s2, d in remaster_entries
                    if s2.id == song.id and d.level_index.value == 4
                ),
                None,
            )
            if re_m is not None:
                return re_m.level
        return diff.level

    grouped: dict[str, list[tuple[Song, SongDifficulty]]] = {}
    for song, diff in entries:
        grouped.setdefault(level_of(song, diff), []).append((song, diff))
    order = sorted(
        grouped, key=lambda lv: (float(lv.rstrip("+")), lv.endswith("+")), reverse=True
    )
    groups = {k: grouped[k] for k in order}

    current_y = START_Y
    for charts in groups.values():
        rows = (len(charts) - 1) // 12 + 1
        current_y += rows * GRID_STEP + 30
    height = current_y + 180

    im = generate_frosted_card(_generate_bg(height, 400), (50, 444, 1350, current_y))
    from PIL import ImageDraw

    dr = ImageDraw.Draw(im)
    if pages is not None:
        dr.text(
            (700, height - 140),
            f"Pages {pages + 1}/2",
            font=font(40, "FOT-NewRodin Pro EB.otf"),
            fill=FONT_BLUE,
            anchor="mm",
        )
    _credit(im, height)

    start_y = START_Y
    for level, charts in groups.items():
        charts.sort(key=lambda pair: pair[1].level_value, reverse=True)
        dr.text(
            (72, start_y + 40),
            level,
            font=font(40, "FOT-NewRodin Pro EB.otf"),
            fill=FONT_BLUE,
            anchor="lm",
            stroke_width=4,
            stroke_fill=(255, 255, 255, 255),
        )
        max_row = 0
        for num, (song, diff) in enumerate(charts):
            row, col = divmod(num, 12)
            max_row = max(max_row, row)
            x = START_X + col * GRID_STEP
            y = start_y + row * GRID_STEP
            is_rem = song.id in remaster_ids
            im.alpha_composite(assets.cover(song.id).resize((80, 80)), (x, y))
            im.alpha_composite(
                assets.pic(
                    "border_table_remaster.png" if is_rem else "border_table_base.png"
                ),
                (x - 5, y - 5),
            )
            dr.text(
                (x + 56, y + 4),
                str(chart_display_id(song, diff)),
                font=font(16, "Torus SemiBold.otf"),
                fill=(138, 0, 226, 255) if is_rem else (255, 255, 255, 255),
                anchor="mm",
            )
        start_y += (max_row + 1) * GRID_STEP + 30
    return im


def _major_type_of_plate(version: str) -> SongType:
    """牌子主类型（maimai_py MaimaiPlates._major_type 同语义）。"""
    from maimai_py import plate_to_version

    if version in ("舞", "霸"):
        return SongType.STANDARD
    pv = plate_to_version.get(version)
    return SongType.DX if pv is not None and pv.value >= 20000 else SongType.STANDARD


def _in_plate_scope(
    song: Song, diff: SongDifficulty, lo: int, hi: int, major_type: SongType
) -> bool:
    return (
        diff.type == major_type
        and diff.version is not None
        and lo <= diff.version <= hi
    )


def _plate_version_range(version: str) -> tuple[int, int] | None:
    from maimai_py import plate_to_version

    if version in ("舞", "霸"):
        vals = [v.value for v in plate_to_version.values() if v.value < 20000]
        return (min(vals), max(vals)) if vals else None
    pv = plate_to_version.get(version)
    if pv is None:
        return None
    nxt = [v.value for v in plate_to_version.values() if v.value > pv.value]
    hi = (min(nxt) - 1) if nxt else 27000
    return (pv.value, hi)


# ---------------------------------------------------------------------------
# 预渲染入口（SUPERUSER 指令与国服更新自动触发共用）
# ---------------------------------------------------------------------------


def _filter_level(
    songs: Sequence[Song], level: str
) -> list[tuple[Song, SongDifficulty]]:
    entries = []
    for song in songs:
        for diff in song.get_difficulties():
            if diff.type != SongType.UTAGE and diff.level == level:
                entries.append((song, diff))
    return entries


async def generate_rating_template(level: str, song_service) -> int:
    """NB 布局生成某等级定数表底图；lv15 走三列大图。返回谱面数。"""
    entries = _filter_level(await song_service.get_all(), level)
    if not entries:
        return 0
    img = _rating_grid_15(entries) if level == "15" else _rating_grid(entries)
    out = rating_table_dir() / f"{level}.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    await asyncio.to_thread(img.save, out)
    return len(entries)


async def generate_plate_template(version: str, kind: str, song_service) -> int:
    """NB 布局生成牌子完成表底图；舞/霸生成两页。返回谱面数。"""
    songs = await song_service.get_all()
    major = _major_type_of_plate(version)
    rng = _plate_version_range(version)
    if rng is None:
        return 0
    lo, hi = rng
    entries = [
        (song, diff)
        for song in songs
        for diff in song.get_difficulties()
        if _in_plate_scope(song, diff, lo, hi, major)
    ]
    if not entries:
        return 0
    out_dir = plate_table_dir()
    out_dir.mkdir(parents=True, exist_ok=True)
    if version in ("舞", "霸"):
        remaster = [
            (song, diff)
            for song in songs
            for diff in song.get_difficulties()
            if diff.type == major and diff.level_index.value == 4
        ]
        boundary = 13
        by_level = _by_level(entries, remaster)
        page_groups = [
            {k: v for k, v in by_level.items() if _lv_key(k) >= boundary},
            {k: v for k, v in by_level.items() if _lv_key(k) < boundary},
        ]
        total = 0
        for pages, group in enumerate(page_groups):
            if not any(group.values()):
                continue
            flat = [pair for charts in group.values() for pair in charts]
            img = _plate_grid(flat, major, remaster_entries=remaster, pages=pages)
            await asyncio.to_thread(img.save, out_dir / f"{version}-{pages + 1}.png")
            total += sum(len(v) for v in group.values())
        return total
    img = _plate_grid(entries, major)
    await asyncio.to_thread(img.save, out_dir / f"{version}{kind}.png")
    return len(entries)


def _by_level(
    entries: Sequence[tuple[Song, SongDifficulty]],
    remaster: Sequence[tuple[Song, SongDifficulty]],
) -> dict[str, list[tuple[Song, SongDifficulty]]]:
    grouped: dict[str, list[tuple[Song, SongDifficulty]]] = {}
    remaster_ids = {s.id for s, _d in remaster}
    for song, diff in entries:
        lv = diff.level
        if song.id in remaster_ids:
            re_m = next(
                (
                    d
                    for s2, d in remaster
                    if s2.id == song.id and d.level_index.value == 4
                ),
                None,
            )
            if re_m is not None:
                lv = re_m.level
        grouped.setdefault(lv, []).append((song, diff))
    return grouped


def _lv_key(lv: str) -> float:
    return float(lv.rstrip("+")) + (0.3 if lv.endswith("+") else 0.0)


async def refresh_all_rating_tables(song_service) -> tuple[int, list[str]]:
    """全部等级（lv7–15）定数表底图；返回 (谱面次, 失败等级)。失败保留旧底图。"""
    from ...constants import LEVEL_LIST

    async with _template_lock:
        total, failed = 0, []
        for lv in LEVEL_LIST[6:]:
            try:
                total += await generate_rating_template(lv, song_service)
            except Exception:
                logger.exception(f"定数表底图生成失败：{lv}")
                failed.append(lv)
        return total, failed


async def refresh_all_plate_tables(song_service) -> tuple[int, list[str]]:
    """全部版本牌种完成表底图（含舞/霸两页）；返回 (谱面次, 失败项)。"""
    from ...constants import PLATE_CHARS, PLATE_KINDS

    async with _template_lock:
        total, failed = 0, []
        for version in PLATE_CHARS:
            for kind in PLATE_KINDS if version in ("舞", "霸") else ("将",):
                try:
                    total += await generate_plate_template(version, kind, song_service)
                except Exception:
                    logger.exception(f"完成表底图生成失败：{version}{kind}")
                    failed.append(f"{version}{kind}")
        return total, failed


_template_lock = asyncio.Lock()
"""预渲染串行锁：CPU 密集，手动指令与自动触发共用同一把。"""


def ensure_dirs() -> None:
    if not assets.static_path().exists():
        return
    rating_table_dir().mkdir(parents=True, exist_ok=True)
    plate_table_dir().mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# 用户查询渲染
# ---------------------------------------------------------------------------


def rating_table_text_bytes(
    level: str, entries: Sequence[tuple[Song, SongDifficulty]]
) -> bytes:
    """`<等级>定数表`（NB DrawRatingTable(level_text=True) 版式）。

    底图存在时直接叠「Level. {level}」大字；缺失时按 NB 布局现算（不落盘）；
    最终按 NB 同款 0.8 缩放输出。坐标对 NB 1400 宽底图原生适配。
    """
    from PIL import ImageDraw

    path = rating_table_dir() / f"{level}.png"
    if path.exists():
        im = Image.open(path).convert("RGBA")
    else:
        im = _rating_grid_15(entries) if level == "15" else _rating_grid(entries)
    dr = ImageDraw.Draw(im)
    dr.text(
        (495, 220),
        "Level.",
        font=font(70, "FOT-NewRodin Pro EB.otf"),
        fill=FONT_BLUE,
        anchor="ld",
        stroke_width=8,
        stroke_fill=(255, 255, 255, 255),
    )
    dr.text(
        (750, 220),
        level,
        font=font(100, "FOT-NewRodin Pro EB.otf"),
        fill=FONT_BLUE,
        anchor="ld",
        stroke_width=8,
        stroke_fill=(255, 255, 255, 255),
    )
    im = im.resize(
        (round(im.size[0] * 0.8), round(im.size[1] * 0.8)), Image.Resampling.LANCZOS
    )
    return image_to_bytes(im)
