"""PIL 公共工具：文本转图、圆角、渐变、图片字节化。"""

import io
from typing import Literal
from functools import lru_cache

from PIL import Image, ImageDraw, ImageFont, ImageFilter

from .fonts import FONT_HAN, font
from .assets import assets
from ...config import NICKNAME

DEFAULT_TEXT_SIZE = 28

# PRiSM PLUS 蓝两档（素材包 UI 取色）：正文/计数蓝 与 大标题蓝
TEXT_BLUE = (124, 129, 255, 255)
TITLE_BLUE = (114, 188, 254, 255)
# circle 主题主色（素材包 UI 取色）
CIRCLE_PINK = (249, 62, 172, 255)

# 行卡文字/曲目 id 按难度配色（Hoshino AssetsImage 同源，三处渲染共用）
DIFF_TEXT_COLORS = [
    (255, 255, 255, 255),
    (255, 255, 255, 255),
    (255, 255, 255, 255),
    (255, 255, 255, 255),
    (138, 0, 226, 255),
]
ID_TEXT_COLORS = [
    (129, 217, 85, 255),
    (245, 189, 21, 255),
    (255, 129, 141, 255),
    (159, 81, 220, 255),
    (138, 0, 226, 255),
]


def credit_text(service: str | None = None) -> str:
    """卡面署名：设计者 + 可选数据源 + 生成者（全部渲染模块共用一份）。"""
    text = "Designed by Yuri-YuzuChaN & BlueDeer233."
    if service:
        text += f" Data from {service}."
    return f"{text} Generated by {NICKNAME or 'awmc-helper'} BOT"


def generate_prism_bg(height: int, separator_y: int | None = None) -> Image.Image:
    """PRiSM PLUS 装饰底图：三色渐变 + aurora/shines/rainbow + pattern 平铺。

    ``separator_y`` 提供时在 (100, y) 叠分割线（表格类版式用）。
    """
    im = tricolor_gradient_prism_plus(1400, height)
    im.alpha_composite(assets.pic("aurora.png"))
    im.alpha_composite(assets.pic("bg_shines.png"), (11, 6))
    im.alpha_composite(assets.pic("rainbow.png"), (318, height - 545))
    im.alpha_composite(assets.pic("rainbow_bottom.png"), (122, height - 305))
    pattern = assets.pic("pattern.png")
    for h in range(height // 358 + 1):
        im.alpha_composite(pattern, (0, (358 + 7) * h))
    if separator_y is not None:
        im.alpha_composite(assets.pic("separator.png"), (100, separator_y))
    return im


# NB base.py 的东亚字宽判定（截断用）；best50 行卡与 nb_chart 曲名截断共用
_CHAR_WIDTHS = [
    (126, 1),
    (159, 0),
    (687, 1),
    (710, 0),
    (711, 1),
    (727, 0),
    (733, 1),
    (879, 0),
    (1154, 1),
    (1161, 0),
    (4347, 1),
    (4447, 2),
    (7467, 1),
    (7521, 0),
    (8369, 1),
    (8426, 0),
    (9000, 1),
    (9002, 2),
    (11021, 1),
    (12350, 2),
    (12351, 1),
    (12438, 2),
    (12442, 0),
    (19893, 2),
    (19967, 1),
    (55203, 2),
    (63743, 1),
    (64106, 2),
    (65039, 1),
    (65059, 0),
    (65131, 2),
    (65279, 1),
    (65376, 2),
    (65500, 1),
    (65510, 2),
    (120831, 1),
    (262141, 2),
    (1114109, 1),
]


def char_width(o: int) -> int:
    """单字符显示宽度（0/1/2）。"""
    if o in (0xE, 0xF):
        return 0
    for num, wid in _CHAR_WIDTHS:
        if o <= num:
            return wid
    return 1


def column_width(text: str) -> int:
    """字符串显示宽度（列数）。"""
    return sum(char_width(ord(ch)) for ch in text)


def truncate_by_width(text: str, limit: int) -> str:
    """按显示宽度截断，超宽加省略号。"""
    if column_width(text) <= limit:
        return text
    res = 0
    out = []
    for ch in text:
        w = char_width(ord(ch))
        if res + w <= limit:
            out.append(ch)
            res += w
        else:
            break
    return "".join(out) + "..."


def truncate_hoshino(text: str, limit: int) -> str:
    """Hoshino 截断规则：显示宽度 >limit 才截，截后保留 ≤limit-1 列再加省略号。

    NB/Hoshino 各卡面（标题/曲师/谱师）统一该双参数语义——直接写
    ``truncate_by_width(text, limit - 1)`` 会把宽度恰为 limit 的文本也截掉。
    """
    if column_width(text) <= limit:
        return text
    return truncate_by_width(text, limit - 1)


def image_to_bytes(img: Image.Image, fmt: Literal["PNG", "JPEG"] = "PNG") -> bytes:
    """Image → bytes（机器人发送统一出口）。"""
    buf = io.BytesIO()
    if fmt == "JPEG":
        img = img.convert("RGB")
    img.save(buf, fmt)
    return buf.getvalue()


def scale_output(img: Image.Image, factor: float = 0.8) -> Image.Image:
    """出图前整体缩放（NB 完成表系版式同款 0.8×LANCZOS：1400 宽底图按
    0.8 缩到 1120 发送）。"""
    return img.resize(
        (round(img.size[0] * factor), round(img.size[1] * factor)),
        Image.Resampling.LANCZOS,
    )


def text_size(text: str, f: ImageFont.FreeTypeFont) -> tuple[int, int]:
    left, top, right, bottom = f.getbbox(text)
    return int(right - left), int(bottom - top)


def fit_text(text: str, f: ImageFont.FreeTypeFont, max_width: int) -> str:
    """超宽文本截断加省略号。"""
    if text_size(text, f)[0] <= max_width:
        return text
    while text and text_size(text + "…", f)[0] > max_width:
        text = text[:-1]
    return text + "…"


def text_to_image(
    text: str,
    size: int = DEFAULT_TEXT_SIZE,
    padding: int = 16,
    font_name: str | None = None,
    fg: str = "#49444d",
    bg: str = "#ffffff",
    max_width: int = 1200,
) -> Image.Image:
    """多行长文本转图（白底黑字），自动换行与宽度截断。"""
    f = font(size, font_name or FONT_HAN)
    line_spacing = int(size * 0.4)
    lines: list[str] = []
    for raw in text.splitlines() or [""]:
        # 整行可容纳则直取（advance 宽一次量完）；超长行才逐字符增量测宽，
        # 消除逐字符全串重测的 O(n²)
        if f.getlength(raw) <= max_width:
            lines.append(raw)
            continue
        current = ""
        width = 0.0
        for ch in raw:
            w = f.getlength(ch)
            if width + w > max_width:
                lines.append(current)
                current = ch
                width = w
            else:
                current += ch
                width += w
        lines.append(current)
    width = max((text_size(line, f)[0] for line in lines), default=0)
    height = len(lines) * size + (len(lines) - 1) * line_spacing
    img = Image.new("RGBA", (width + padding * 2, height + padding * 2), bg)
    draw = ImageDraw.Draw(img)
    y = padding
    for line in lines:
        draw.text((padding, y), line, font=f, fill=fg)
        y += size + line_spacing
    return img


def rounded_mask(size: tuple[int, int], radius: int) -> Image.Image:
    """圆角蒙版（贴图裁圆角用）。"""
    mask = Image.new("L", size, 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        (0, 0, size[0] - 1, size[1] - 1), radius, fill=255
    )
    return mask


@lru_cache(maxsize=128)
def _gradient_line(height: int) -> Image.Image:
    """1×height 渐变线（按高度缓存，同一底图高度多次渲染零重算；只读共用）。"""
    colors_list = [
        (0.00, (255, 255, 255)),
        (0.14, (255, 255, 255)),
        (0.24, (255, 213, 207)),
        (0.46, (255, 213, 207)),
        (0.56, (255, 197, 213)),
        (0.67, (234, 171, 255)),
        (0.85, (114, 188, 254)),
        (0.95, (101, 242, 223)),
        (1.00, (101, 242, 223)),
    ]
    line = Image.new("RGBA", (1, height))
    for y in range(height):
        t = 1.0 - (y / (height - 1)) if height > 1 else 0
        for i in range(len(colors_list) - 1):
            p1, c1 = colors_list[i]
            p2, c2 = colors_list[i + 1]
            if p1 <= t <= p2:
                rel = (t - p1) / (p2 - p1)
                rgb = tuple(int(c1[j] + (c2[j] - c1[j]) * rel) for j in range(3))
                line.putpixel((0, y), rgb)
                break
    return line


def tricolor_gradient_prism_plus(width: int, height: int) -> Image.Image:
    """垂直 PRiSM PLUS 三色渐变底（NB core/image/tools.py 同源移植）。

    先逐行放样 1×height 再拉伸到目标宽，避免逐像素画大图。
    """
    return _gradient_line(height).resize((width, height), Image.Resampling.BICUBIC)


def generate_frosted_card(
    im: Image.Image,
    box: tuple[int, int, int, int],
    shadow_offset: tuple[int, int] = (10, 10),
    alpha: float = 0.4,
) -> Image.Image:
    """在 im 的 box 区域叠一块圆角毛玻璃卡（NB 同源移植，牌子进度总览用）。"""
    if alpha < 0 or alpha > 1:
        raise ValueError("alpha 应在 0-1 之间")
    roi = im.crop(box)
    roi_w, roi_h = roi.size

    frosted = roi.filter(ImageFilter.GaussianBlur(4))
    white_layer = Image.new("RGBA", (roi_w, roi_h), (255, 255, 255, int(255 * alpha)))
    card = Image.alpha_composite(frosted, white_layer)

    mask = Image.new("L", (roi_w, roi_h), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, roi_w, roi_h), radius=25, fill=255)

    # 投影
    shadow_w = roi_w + 10 + abs(shadow_offset[0])
    shadow_h = roi_h + 10 + abs(shadow_offset[1])
    shadow = Image.new("RGBA", (shadow_w, shadow_h), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle(
        (15, 15, 15 + roi_w, 15 + roi_h), radius=25, fill=(0, 0, 0, 50)
    )
    shadow_layer = shadow.filter(ImageFilter.GaussianBlur(3))

    temp_layer = Image.new("RGBA", im.size, (0, 0, 0, 0))
    shadow_pos = (box[0] + shadow_offset[0] - 15, box[1] + shadow_offset[1] - 15)
    temp_layer.paste(shadow_layer, shadow_pos)
    temp_layer.paste(card, (box[0], box[1]), mask=mask)

    return Image.alpha_composite(im, temp_layer)
